/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/airports/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Airport Metrics */
        get: operations["get_airport_metrics_api_airports__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/airports/{code}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Airport Score */
        get: operations["get_airport_score_api_airports__code__score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/airports/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Airports */
        post: operations["compare_airports_api_airports_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scoring/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scoring Methodology */
        get: operations["get_scoring_methodology_api_scoring_methodology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/{region}/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Region Ranking */
        get: operations["get_region_ranking_api_regions__region__ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tts/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tts Status
         * @description Returns TTS capability status without exposing secrets.
         */
        get: operations["tts_status_api_tts_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synthesize Speech
         * @description Converts text to speech using the configured provider.
         *     Returns audio/mpeg stream.
         */
        post: operations["synthesize_speech_api_tts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Absent */
        Absent: {
            /**
             * Kind
             * @default absent
             * @constant
             */
            kind: "absent";
            /**
             * Reason
             * @enum {string}
             */
            reason: "NOT_PUBLISHED" | "PROVIDER_FAILED" | "NO_DEPARTURES" | "OUT_OF_SCOPE";
            /** Detail */
            detail: string;
            /** Attempted */
            attempted: string[];
        };
        /** AirportContext */
        AirportContext: {
            nas_delay_program?: components["schemas"]["DelayProgram"] | null;
            weather?: components["schemas"]["WeatherContext"] | null;
            connectivity?: components["schemas"]["ConnectivityContext"] | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** AirportMetrics */
        AirportMetrics: {
            /**
             * Airport Code
             * @enum {string}
             */
            airport_code: "BOS" | "BDL" | "PVD" | "PWM" | "LAX" | "SNA" | "ANC" | "SFO" | "JFK";
            /**
             * Airport Name
             * @default
             */
            airport_name: string;
            /** Passenger Volume */
            passenger_volume: components["schemas"]["Present_int_"] | components["schemas"]["Absent"];
            /** Previous Passenger Volume */
            previous_passenger_volume: components["schemas"]["Present_int_"] | components["schemas"]["Absent"];
            /** Annual Operations */
            annual_operations: components["schemas"]["Present_int_"] | components["schemas"]["Absent"];
            /** Delayed Flights Pct */
            delayed_flights_pct: components["schemas"]["Present_float_"] | components["schemas"]["Absent"];
            /** Average Delay Minutes */
            average_delay_minutes: components["schemas"]["Present_float_"] | components["schemas"]["Absent"];
            /** Long Haul Flights */
            long_haul_flights: components["schemas"]["Present_int_"] | components["schemas"]["Absent"];
            /** Total Departures */
            total_departures: components["schemas"]["Present_int_"] | components["schemas"]["Absent"];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            /** Sources */
            readonly sources: string[];
            /** Data Period */
            readonly data_period: string;
            /** Completeness Score */
            readonly completeness_score: number;
            /**
             * Freshness
             * @enum {string}
             */
            readonly freshness: "live" | "sample" | "mixed";
        };
        /** AirportMetricsResponse */
        AirportMetricsResponse: {
            metrics: components["schemas"]["AirportMetrics"];
            context?: components["schemas"]["AirportContext"] | null;
        };
        /** AirportScore */
        AirportScore: {
            /**
             * Airport Code
             * @enum {string}
             */
            airport_code: "BOS" | "BDL" | "PVD" | "PWM" | "LAX" | "SNA" | "ANC" | "SFO" | "JFK";
            /**
             * Airport Name
             * @default
             */
            airport_name: string;
            /** Opportunity Score */
            opportunity_score: components["schemas"]["Present_float_"] | components["schemas"]["Absent"];
            /** Demand Growth Score */
            demand_growth_score: components["schemas"]["Present_float_"] | components["schemas"]["Absent"];
            /** Congestion Score */
            congestion_score: components["schemas"]["Present_float_"] | components["schemas"]["Absent"];
            /** Delay Pressure Score */
            delay_pressure_score: components["schemas"]["Present_float_"] | components["schemas"]["Absent"];
            /** Capacity Pressure Score */
            capacity_pressure_score: components["schemas"]["Present_float_"] | components["schemas"]["Absent"];
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "HIGH" | "MEDIUM" | "LOW";
            context?: components["schemas"]["AirportContext"] | null;
            /** Snapshot At */
            snapshot_at: string;
            /** Assumptions */
            readonly assumptions: string[];
            /** Limitations */
            readonly limitations: string[];
            /** Sources */
            readonly sources: string[];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * Conversation Id
             * @default default
             */
            conversation_id: string;
            /**
             * Voice Confidence
             * @description Speech-recognition confidence (0-1). None means typed input.
             */
            voice_confidence?: number | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Message */
            message: string;
            /** Airports */
            airports: string[];
            /** Analysis Type */
            analysis_type?: string | null;
            /**
             * Scores
             * @default {}
             */
            scores: {
                [key: string]: components["schemas"]["AirportScore"];
            };
            /**
             * Sources
             * @default []
             */
            sources: string[];
            /**
             * Assumptions
             * @default []
             */
            assumptions: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            /**
             * Confidence
             * @default LOW
             * @enum {string}
             */
            confidence: "HIGH" | "MEDIUM" | "LOW";
            /**
             * Data Freshness
             * @default live
             * @enum {string}
             */
            data_freshness: "live" | "mixed" | "sample";
            /**
             * Evidence
             * @default []
             */
            evidence: (components["schemas"]["MetricsResult"] | components["schemas"]["ScoreResult"] | components["schemas"]["ComparisonResult"] | components["schemas"]["RankingResult"] | components["schemas"]["LongHaulResult"] | components["schemas"]["UnmetDemandResult"] | components["schemas"]["SimulationResult"] | components["schemas"]["ToolRejection"])[];
            /**
             * Evidence Origin
             * @default none
             * @enum {string}
             */
            evidence_origin: "this_turn" | "carried" | "none";
            needs_confirmation?: components["schemas"]["Confirmation"] | null;
        };
        /** CompareRequest */
        CompareRequest: {
            /** Airport Codes */
            airport_codes: ("BOS" | "BDL" | "PVD" | "PWM" | "LAX" | "SNA" | "ANC" | "SFO" | "JFK")[];
        };
        /** ComparisonResult */
        ComparisonResult: {
            /** Airports */
            airports: string[];
            /** Snapshot At */
            snapshot_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "comparison";
            /** Rows */
            rows: components["schemas"]["ComparisonRow"][];
            /** Highest Congestion */
            highest_congestion: string | null;
            /** Highest Opportunity Score */
            highest_opportunity_score: string | null;
            /** Period Warning */
            period_warning: string | null;
        };
        /** ComparisonRow */
        ComparisonRow: {
            /**
             * Airport Code
             * @enum {string}
             */
            airport_code: "BOS" | "BDL" | "PVD" | "PWM" | "LAX" | "SNA" | "ANC" | "SFO" | "JFK";
            score: components["schemas"]["AirportScore"];
            metrics: components["schemas"]["AirportMetrics"];
            context?: components["schemas"]["AirportContext"] | null;
        };
        /** ConfirmOption */
        ConfirmOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** Confirmation */
        Confirmation: {
            /** Prompt */
            prompt: string;
            /** Options */
            options: components["schemas"]["ConfirmOption"][];
        };
        /** ConnectivityContext */
        ConnectivityContext: {
            /** Distinct Destinations */
            distinct_destinations: number;
            /** International Destinations */
            international_destinations: number;
            /** Long Haul Route Count */
            long_haul_route_count?: number | null;
        };
        /** DelayProgram */
        DelayProgram: {
            /** Airport Icao */
            airport_icao: string;
            /** Program */
            program: string;
            /** Reason */
            reason: string;
            /** Avg Delay */
            avg_delay: string;
            /** Updated At */
            updated_at: string;
        };
        /** Derived */
        Derived: {
            /**
             * Kind
             * @default derived
             * @constant
             */
            kind: "derived";
            /** Method */
            method: string;
            /** Inputs */
            inputs: string[];
            /** Period */
            period: string;
            /** Sources */
            sources: string[];
            /**
             * Freshness
             * @enum {string}
             */
            freshness: "live" | "sample" | "mixed";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
        };
        /** Live */
        Live: {
            /**
             * Kind
             * @default live
             * @constant
             */
            kind: "live";
            /** Source */
            source: string;
            /** Period */
            period: string;
            /** Fetched At */
            fetched_at: string;
        };
        /** LongHaulResult */
        LongHaulResult: {
            /** Airports */
            airports: string[];
            /** Snapshot At */
            snapshot_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "long_haul";
            /** Long Haul Pct */
            long_haul_pct: components["schemas"]["Present_float_"] | components["schemas"]["Absent"];
            /** Basis */
            basis?: string | null;
            /**
             * Threshold Statute Miles
             * @default 3000
             */
            threshold_statute_miles: number;
        };
        /** MetricsResult */
        MetricsResult: {
            /** Airports */
            airports: string[];
            /** Snapshot At */
            snapshot_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "metrics";
            metrics: components["schemas"]["AirportMetrics"];
            context?: components["schemas"]["AirportContext"] | null;
        };
        /** Present[float] */
        Present_float_: {
            /**
             * Kind
             * @default present
             * @constant
             */
            kind: "present";
            /** Value */
            value: number;
            /** Origin */
            origin: components["schemas"]["Live"] | components["schemas"]["Sample"] | components["schemas"]["Derived"] | components["schemas"]["Proxy"] | components["schemas"]["Scenario"];
        };
        /** Present[int] */
        Present_int_: {
            /**
             * Kind
             * @default present
             * @constant
             */
            kind: "present";
            /** Value */
            value: number;
            /** Origin */
            origin: components["schemas"]["Live"] | components["schemas"]["Sample"] | components["schemas"]["Derived"] | components["schemas"]["Proxy"] | components["schemas"]["Scenario"];
        };
        /** Proxy */
        Proxy: {
            /**
             * Kind
             * @default proxy
             * @constant
             */
            kind: "proxy";
            /** Method */
            method: string;
            /** Inputs */
            inputs: string[];
            /** Assumption */
            assumption: string;
            /** Period */
            period: string;
            /** Sources */
            sources: string[];
            /**
             * Freshness
             * @enum {string}
             */
            freshness: "live" | "sample" | "mixed";
        };
        /** RankingResult */
        RankingResult: {
            /** Airports */
            airports: string[];
            /** Snapshot At */
            snapshot_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ranking";
            /** Ranked */
            ranked: components["schemas"]["AirportScore"][];
            /** Region */
            region: string;
            /** Peer Note */
            peer_note: string;
        };
        /** Sample */
        Sample: {
            /**
             * Kind
             * @default sample
             * @constant
             */
            kind: "sample";
            /** Source */
            source: string;
            /** Period */
            period: string;
            /** Citation */
            citation: string;
        };
        /** Scenario */
        Scenario: {
            /**
             * Kind
             * @default scenario
             * @constant
             */
            kind: "scenario";
            /** Adjustment */
            adjustment: string;
            /** Baseline Origin */
            baseline_origin: components["schemas"]["Live"] | components["schemas"]["Sample"] | components["schemas"]["Derived"] | components["schemas"]["Proxy"] | components["schemas"]["Scenario"];
            /** Period */
            period: string;
        };
        /** ScoreResult */
        ScoreResult: {
            /** Airports */
            airports: string[];
            /** Snapshot At */
            snapshot_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "score";
            score: components["schemas"]["AirportScore"];
            context?: components["schemas"]["AirportContext"] | null;
        };
        /** ScoringMethodology */
        ScoringMethodology: {
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Component Labels */
            component_labels: {
                [key: string]: string;
            };
            /** Rules */
            rules: string[];
        };
        /** SimulationResult */
        SimulationResult: {
            /** Airports */
            airports: string[];
            /** Snapshot At */
            snapshot_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "simulation";
            baseline_score: components["schemas"]["AirportScore"];
            simulated_score: components["schemas"]["AirportScore"];
            /** Growth Adjustment */
            growth_adjustment: number;
            /** Delta Opportunity */
            delta_opportunity: number | null;
        };
        /** ToolRejection */
        ToolRejection: {
            /** Airports */
            airports: string[];
            /** Snapshot At */
            snapshot_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rejection";
            /** Tool Name */
            tool_name: string;
            /** Reason */
            reason: string;
        };
        /** TtsRequest */
        TtsRequest: {
            /** Text */
            text: string;
        };
        /** UnmetDemandResult */
        UnmetDemandResult: {
            /** Airports */
            airports: string[];
            /** Snapshot At */
            snapshot_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "unmet_demand";
            /** Unmet Demand Index */
            unmet_demand_index: components["schemas"]["Present_float_"] | components["schemas"]["Absent"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherContext */
        WeatherContext: {
            /** Flight Category */
            flight_category: string;
            /** Wind */
            wind: string;
            /** Visibility */
            visibility: string;
            /** Remarks */
            remarks: string;
            /** Observation Time */
            observation_time: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_airport_metrics_api_airports__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_airport_score_api_airports__code__score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportScore"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_airports_api_airports_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scoring_methodology_api_scoring_methodology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringMethodology"];
                };
            };
        };
    };
    get_region_ranking_api_regions__region__ranking_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tts_status_api_tts_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    synthesize_speech_api_tts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TtsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
